<?php
/**
 * This file is part of the DataMapper package
 *
 * Copyright (c) 2012 Hannes Forsgård
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Hannes Forsgård <hannes.forsgard@gmail.com>
 *
 * @package phplibphone
 */
namespace itbz\phplibphone\Swe;
use itbz\phplibphone\PhoneArea as PhoneAreaBase;


/**
 * Lookup sweidsh national destination codes
 * @package phplibphone
 */
class PhoneArea extends PhoneAreaBase
{

    /**
     * Collection of area codes
     *  @var array $codes
     */
    protected $codes = array(
        '46' => array(
            '10' => 'Lokalt direktval företagsväxlar',
            '11' => 'Norrköping',
            '120' => 'Åtvidaberg',
            '121' => 'Söderköping',
            '122' => 'Finspång',
            '123' => 'Valdemarsvik',
            '125' => 'Vikbolandet',
            '13' => 'Linköping',
            '140' => 'Tranås',
            '141' => 'Motala',
            '142' => 'Mjölby/Skänninge/Boxholm',
            '143' => 'Vadstena',
            '144' => 'Ödeshög',
            '150' => 'Katrineholm',
            '151' => 'Vingåker',
            '152' => 'Strängnäs',
            '155' => 'Nyköping/Oxelösund',
            '156' => 'Trosa/Vagnhärad',
            '157' => 'Flen/Malmköping',
            '158' => 'Gnesta',
            '159' => 'Mariefred',
            '16' => 'Eskilstuna/Torshälla',
            '171' => 'Enköping',
            '173' => 'Öregrund/Östhammar',
            '174' => 'Alunda',
            '175' => 'Hallstavik/Rimbo',
            '176' => 'Norrtälje',
            '18' => 'Uppsala',
            '19' => 'Örebro/Kumla',
            '20' => 'Frisamtal',
            '200' => 'Frisamtal',
            '21' => 'Västerås',
            '220' => 'Hallstahammar/Surahammar',
            '221' => 'Köping',
            '222' => 'Skinnskatteberg',
            '223' => 'Fagersta/Norberg',
            '224' => 'Sala/Heby',
            '225' => 'Hedemora/Säter',
            '226' => 'Avesta/Krylbo',
            '227' => 'Kungsör',
            '23' => 'Falun',
            '240' => 'Ludvika/Smedjebacken',
            '241' => 'Gagnef/Floda',
            '243' => 'Borlänge',
            '246' => 'Svärdsjö/Enviken',
            '247' => 'Leksand/Insjön',
            '248' => 'Rättvik',
            '250' => 'Mora/Orsa',
            '251' => 'Älvdalen',
            '253' => 'Idre/Särna',
            '258' => 'Furudal',
            '26' => 'Gävle/Sandviken',
            '270' => 'Söderhamn',
            '271' => 'Alfta/Edsbyn',
            '278' => 'Bollnäs',
            '280' => 'Malung',
            '281' => 'Vansbro',
            '290' => 'Hofors/Storvik',
            '291' => 'Hedesunda/Österfärnebo',
            '292' => 'Tärnsjö/Östervåla',
            '293' => 'Tierp/Söderfors',
            '294' => 'Karlsholmsbruk/Skärplinge',
            '295' => 'Örbyhus/Dannemora',
            '297' => 'Ockelbo/Hamrånge',
            '300' => 'Kungsbacka',
            '301' => 'Hindås',
            '302' => 'Lerum',
            '303' => 'Kungälv',
            '304' => 'Orust/Tjörn',
            '31' => 'Göteborg',
            '320' => 'Kinna',
            '321' => 'Ulricehamn',
            '322' => 'Alingsås/Vårgårda',
            '325' => 'Svenljunga/Tranemo',
            '33' => 'Borås',
            '340' => 'Varberg',
            '345' => 'Hyltebruk/Torup',
            '346' => 'Falkenberg',
            '35' => 'Halmstad',
            '36' => 'Jönköping/Huskvarna',
            '370' => 'Värnamo',
            '371' => 'Gislaved/Anderstorp',
            '372' => 'Ljungby',
            '380' => 'Nässjö',
            '381' => 'Eksjö',
            '382' => 'Sävsjö',
            '383' => 'Vetlanda',
            '390' => 'Gränna',
            '392' => 'Mullsjö',
            '393' => 'Vaggeryd',
            '40' => 'Malmö',
            '410' => 'Trelleborg',
            '411' => 'Ystad',
            '413' => 'Eslöv/Höör',
            '414' => 'Simrishamn',
            '415' => 'Hörby',
            '416' => 'Sjöbo',
            '417' => 'Tomelilla',
            '418' => 'Landskrona/Svalöv',
            '42' => 'Helsingborg/Höganäs',
            '430' => 'Laholm',
            '431' => 'Ängelholm/Båstad',
            '433' => 'Markaryd/Strömsnäsbruk',
            '435' => 'Klippan/Perstorp',
            '44' => 'Kristianstad',
            '451' => 'Hässleholm',
            '454' => 'Karlshamn/Olofström',
            '455' => 'Karlskrona',
            '456' => 'Sölvesborg/Bromölla',
            '457' => 'Ronneby',
            '459' => 'Ryd',
            '46' => 'Lund',
            '470' => 'Växjö',
            '471' => 'Emmaboda',
            '472' => 'Alvesta/Rydaholm',
            '474' => 'Åseda/Lenhovda',
            '476' => 'Älmhult',
            '477' => 'Tingsryd',
            '478' => 'Lessebo',
            '479' => 'Osby',
            '480' => 'Kalmar',
            '481' => 'Nybro',
            '485' => 'Öland',
            '486' => 'Torsås',
            '490' => 'Västervik',
            '491' => 'Oskarshamn/Högsby',
            '492' => 'Vimmerby',
            '493' => 'Gamleby',
            '494' => 'Kisa',
            '495' => 'Hultsfred/Virserum',
            '496' => 'Mariannelund',
            '498' => 'Gotland',
            '499' => 'Mönsterås',
            '500' => 'Skövde',
            '501' => 'Mariestad',
            '502' => 'Tidaholm',
            '503' => 'Hjo',
            '504' => 'Tibro',
            '505' => 'Karlsborg',
            '506' => 'Töreboda/Hova',
            '510' => 'Lidköping',
            '511' => 'Skara/Götene',
            '512' => 'Vara/Nossebro',
            '513' => 'Herrljunga',
            '514' => 'Grästorp',
            '515' => 'Falköping',
            '520' => 'Trollhättan',
            '521' => 'Vänersborg',
            '522' => 'Uddevalla',
            '523' => 'Lysekil',
            '524' => 'Munkedal',
            '525' => 'Grebbestad',
            '526' => 'Strömstad',
            '528' => 'Färgelanda',
            '530' => 'Mellerud',
            '531' => 'Bengtsfors',
            '532' => 'Åmål',
            '533' => 'Säffle',
            '534' => 'Ed',
            '54' => 'Karlstad',
            '550' => 'Kristinehamn',
            '551' => 'Gullspång',
            '552' => 'Deje',
            '553' => 'Molkom',
            '554' => 'Kil',
            '555' => 'Grums',
            '560' => 'Torsby',
            '563' => 'Hagfors/Munkfors',
            '564' => 'Sysslebäck',
            '565' => 'Sunne',
            '570' => 'Arvika',
            '571' => 'Charlottenberg/Åmotfors',
            '573' => 'Årjäng',
            '580' => 'Kopparberg',
            '581' => 'Lindesberg',
            '582' => 'Hallsberg',
            '583' => 'Askersund',
            '584' => 'Laxå',
            '585' => 'Fjugesta/Svartå',
            '586' => 'Karlskoga/Degerfors',
            '587' => 'Nora',
            '589' => 'Arboga',
            '590' => 'Filipstad',
            '591' => 'Hällefors/Grythyttan',
            '60' => 'Sundsvall/Timrå',
            '611' => 'Härnösand',
            '612' => 'Kramfors',
            '613' => 'Ullånger',
            '620' => 'Sollefteå',
            '621' => 'Junsele',
            '622' => 'Näsåker',
            '623' => 'Ramsele',
            '624' => 'Backe',
            '63' => 'Östersund',
            '640' => 'Krokom',
            '642' => 'Lit',
            '643' => 'Hallen/Oviken',
            '644' => 'Hammerdal',
            '645' => 'Föllinge',
            '647' => 'Åre/Järpen',
            '650' => 'Hudiksvall',
            '651' => 'Ljusdal',
            '652' => 'Bergsjö',
            '653' => 'Delsbo',
            '657' => 'Los',
            '660' => 'Örnsköldsvik',
            '661' => 'Bredbyn',
            '662' => 'Björna',
            '663' => 'Husum',
            '670' => 'Strömsund',
            '671' => 'Hoting',
            '672' => 'Gäddede',
            '680' => 'Sveg',
            '682' => 'Rätan',
            '684' => 'Hede/Funäsdalen',
            '687' => 'Svenstavik',
            '690' => 'Ånge',
            '691' => 'Torpshammar',
            '692' => 'Liden',
            '693' => 'Bräcke/Gällö',
            '695' => 'Stugun',
            '696' => 'Hammarstrand',
            '70' => 'MOBILE',
            '72' => 'MOBILE',
            '73' => 'MOBILE',
            '74' => 'Personsökning',
            '75' => 'Personliga nummertjänster',
            '76' => 'MOBILE',
            '77' => 'Tjänster med delad kostnad',
            '78' => 'Teleoperatörers tjänster',
            '8' => 'Stockholm',
            '90' => 'Umeå',
            '900' => 'Betalsamtal',
            '910' => 'Skellefteå',
            '911' => 'Piteå',
            '912' => 'Byske',
            '913' => 'Lövånger',
            '914' => 'Burträsk',
            '915' => 'Bastuträsk',
            '916' => 'Jörn',
            '918' => 'Norsjö',
            '920' => 'Luleå',
            '921' => 'Boden',
            '922' => 'Haparanda',
            '923' => 'Kalix',
            '924' => 'Råneå',
            '925' => 'Lakaträsk',
            '926' => 'Överkalix',
            '927' => 'Övertorneå',
            '928' => 'Harads',
            '929' => 'Älvsbyn',
            '930' => 'Nordmaling',
            '932' => 'Bjurholm',
            '933' => 'Vindeln',
            '934' => 'Robertsfors',
            '935' => 'Vännäs',
            '939' => 'Betalsamtal',
            '940' => 'Vilhelmina',
            '941' => 'Åsele',
            '942' => 'Dorotea',
            '943' => 'Fredrika',
            '944' => 'Betalsamtal',
            '950' => 'Lycksele',
            '951' => 'Storuman',
            '952' => 'Sorsele',
            '953' => 'Malå',
            '954' => 'Tärnaby',
            '960' => 'Arvidsjaur',
            '961' => 'Arjeplog',
            '969' => 'Telefonautomat',
            '970' => 'Gällivare',
            '971' => 'Jokkmokk',
            '973' => 'Porjus',
            '975' => 'Hakkas',
            '976' => 'Vuollerim',
            '977' => 'Korpilombolo',
            '978' => 'Pajala',
            '980' => 'Kiruna',
            '981' => 'Vittangi',
            '99' => 'Massanrop',        
        )
    );

}
